general {
    hide_cursor = true
    disable_loading_bar = true
    no_fade_in = false
    no_fade_out = false
    immediate_render = true
}

background {
    monitor =
    path = /home/shizu/Pictures/Wallpapers/dominik-mayer-17.jpg

    blur_passes = 2
    blur_size = 6
    brightness = 0.65
    contrast = 0.9
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%I:%M %p')"

    color = rgba(229, 225, 233, 1)

    font_size = 64
    font_family = MesloLGLDZ Nerd Font

    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %B %d')"

    color = rgba(199, 196, 220, 1)

    font_size = 18
    font_family = MesloLGLDZ Nerd Font

    position = 0, 55
    halign = center
    valign = center
}

input-field {
    monitor =

    size = 280, 55
    outline_thickness = 2

    dots_size = 0.25
    dots_spacing = 0.15
    dots_center = true

    outer_color = rgba(197, 192, 255, 1)
    inner_color = rgba(19, 19, 24, 1)
    font_color = rgba(229, 225, 233, 1)

    fade_on_empty = false
    rounding = 14

    placeholder_text = <i>Password</i>
    fail_text = <i>$FAIL</i>

    position = 0, -60
    halign = center
    valign = center
}
