background = 0xCC180B18
base = 0xCC261026
text = 0xFFFFE6F2
alternate_base = 0xCC321532
bright_text = 0xFFFFFFFF

accent = 0xFFFF69B4
accent_secondary = 0xFFFF1493

rounding_large = 18
rounding_small = 10
