hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    -- hl.exec_cmd("hyprpm reload")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("udiskie")
    hl.exec_cmd("steam")
    hl.exec_cmd("vesktop")
    hl.exec_cmd("zen-browser")
    hl.exec_cmd("sleep 3 && arch-update --tray")
    hl.exec_cmd("pkill blueman-applet")
    hl.exec_cmd("pkill nm-applet")
end)
