// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1788051032);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.jxl", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1788051030);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 177);
user_pref("browser.newtabpage.activity-stream.impressionId", "{107fdc84-eb4e-44eb-a330-8acc13f04820}");
user_pref("browser.newtabpage.activity-stream.newtabWallpapers.user.enabled.migrated", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1788051030);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1788051032221");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1788072632221");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1788051031");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20260818101929");
user_pref("browser.startup.homepage_override.mstone", "154.0");
user_pref("browser.startup.lastColdStartupCheck", 1788051031);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"ai-window-toggle\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"],\"zen-sidebar-top-buttons\":[\"zen-toggle-compact-mode\"],\"zen-sidebar-foot-buttons\":[\"downloads-button\",\"zen-workspaces-button\",\"zen-create-new-button\"]},\"seen\":[\"ai-window-toggle\",\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"zen-sidebar-foot-buttons\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":25,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 7);
user_pref("captchadetection.lastSubmission", 1788051);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "109823b8-9902-4af9-9710-ac26b71fec49");
user_pref("datareporting.dau.cachedUsageProfileID", "1bb3e681-5165-4eb0-84a8-97a1fa48ac91");
user_pref("distribution.iniFile.exists.appversion", "1.21.15b");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "31ef827dc4ac4301a51f934031d02460");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.lastAppBuildId", "20260818101929");
user_pref("extensions.lastAppVersion", "1.21.15b");
user_pref("extensions.lastPlatformVersion", "154.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"65f2cd99-0492-4e61-9e08-05526cbf6aa4\",\"ipp-activator@mozilla.com\":\"ae8d4274-ddd3-4023-976a-c1636cbbf06c\",\"pictureinpicture@mozilla.org\":\"4714f45f-7adc-47dc-81ef-e112a9a3f499\",\"addons-search-detection@mozilla.com\":\"6d0bf172-8534-4e01-ae42-16d60524809e\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"5a7a57e1-b917-4efb-948a-00ef00fd9eba\",\"default-theme@mozilla.org\":\"e9130465-35d6-45f8-ba8d-625a2fdaa72b\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.firstUpdateComplete", true);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 5);
user_pref("nimbus.migrations.init-started", 1);
user_pref("nimbus.profileId", "d353c8ca-d416-42fa-ba71-2a1d65702df0");
user_pref("nimbus.rollouts.enabled", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.globalprivacycontrol.was_ever_enabled", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("privacy.trackingprotection.allow_list.hasUserInteractedWithETPSettings", true);
user_pref("services.settings.base_attachments_url", "https://firefox.settings.services.mozilla.com/v2|https://firefox-settings-attachments.cdn.mozilla.net/");
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"bookmarksExpandedFolders\":[],\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.visibility", "hide-on-close");
user_pref("signon.storage.rust.active", true);
user_pref("toolkit.profiles.newProfileSubmitted", true);
user_pref("toolkit.profiles.storeID", "e1abfaba");
user_pref("toolkit.startup.last_success", 1788051029);
user_pref("toolkit.telemetry.cachedClientID", "99bd2b65-270f-4548-9e2c-cacfa7a7b8a4");
user_pref("toolkit.telemetry.cachedProfileGroupID", "c463dc25-242b-4f2e-951a-656b90c76234");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("zen.keyboard.shortcuts.version", 20);
user_pref("zen.mods.last-update", 1788051031);
user_pref("zen.mods.milestone", "1.21.15b");
user_pref("zen.mods.updated-value-observer", true);
user_pref("zen.session-store.last-build-id", "20260818101929");
user_pref("zen.ui.migration.compact-mode-button-added", true);
user_pref("zen.ui.migration.version", 7);
user_pref("zen.updates.last-build-id", "20260818101929");
user_pref("zen.updates.last-version", "1.21.15b");
user_pref("zen.welcome-screen.seen", true);
user_pref("zen.workspaces.active", "{23da9609-4e47-4cd2-8eed-76ed7eeea78d}");
