$background = rgb({{ colors.background.default.red }}, {{ colors.background.default.green }}, {{ colors.background.default.blue }})
$foreground = rgb({{ colors.on_background.default.red }}, {{ colors.on_background.default.green }}, {{ colors.on_background.default.blue }})
$accent = rgb({{ colors.primary.default.red }}, {{ colors.primary.default.green }}, {{ colors.primary.default.blue }})
$accent2 = rgb({{ colors.secondary.default.red }}, {{ colors.secondary.default.green }}, {{ colors.secondary.default.blue }})
