font=Sans 11

background-color={{ colors.background.default.hex }}aa
text-color={{ colors.on_background.default.hex }}ff
border-color={{ colors.primary.default.hex }}ff
progress-color=over {{ colors.primary.default.hex }}ff

border-size=2
border-radius=12

width=380
height=120
padding=14
margin=18
outer-margin=0

default-timeout=5000
ignore-timeout=0

max-visible=5
layer=overlay

icons=1
max-icon-size=48

anchor=top-right

group-by=app-name
format=<b>%s</b>\n%b

[urgency=low]
border-color={{ colors.secondary.default.hex }}ff
default-timeout=3000

[urgency=normal]
border-color={{ colors.primary.default.hex }}ff
default-timeout=5000

[urgency=critical]
background-color={{ colors.error_container.default.hex }}ff
border-color={{ colors.error.default.hex }}ff
text-color={{ colors.on_error_container.default.hex }}ff
default-timeout=0
